name: price_app
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flex_color_scheme: ^8.4.0
  easy_localization: ^3.0.8
  timezone: ^0.10.1
  flutter_native_splash: ^2.4.7
  overlay_support: ^2.1.0
  go_router: ^17.0.0
  dio: ^5.9.0
  get_it: ^9.2.0
  logger: ^2.6.2
  provider: ^6.1.5+1
  smooth_page_indicator: ^2.0.1
  lottie: ^3.3.2
  shared_preferences: ^2.5.3
  gap: ^3.0.1
  flutter_svg: ^2.2.3
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  collection: ^1.19.1
  dw_image_picker: ^1.2.18
  photo_view: ^0.15.0
  modal_bottom_sheet: ^3.0.0
  url_launcher: ^6.3.2
  flutter_spinkit: ^5.2.2
  random_avatar: ^0.0.8
  webview_flutter: ^4.13.0
  flutter_platform_alert: ^0.8.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  phone_numbers_parser: ^9.0.17
  timeago: ^3.7.1
  hexcolor: ^3.0.2
  flutter_vibrate:
    git:
      url: https://github.com/saytoonz/flutter_vibrate.git
      ref: android-upgrade-and-java_to_kotlin
  firebase_messaging: ^16.0.4
  family_bottom_sheet: ^0.1.0
  share_plus: ^12.0.1
  flutter_exit_app: ^2.0.0
  package_info_plus: ^9.0.0
  firebase_remote_config: ^6.1.4
  flutter_offline: ^6.0.0
  pinput: ^6.0.1
  day_month_picker: ^1.0.3
  geolocator: ^14.0.1
  geocoding: ^4.0.0
  carousel_slider: ^5.1.1
  better_player_plus: ^1.1.5
  flutter_map_cancellable_tile_provider: ^3.1.1
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  network_info_plus: ^7.0.0
  device_info_plus: ^12.3.0
  #hive: ^2.2.3
  #hive_flutter: ^1.1.0
  email_validator: ^3.0.0
  flutter_map_dragmarker: ^8.0.3
  either_dart: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  freezed: ^2.5.8
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter_native_splash:
  color: "#ffffff"
  image: assets/icon/logo-mark.png
  fullscreen: true
  android: true
  android_gravity: center
  ios: true
  ios_content_mode: center

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/png/
    - assets/jpeg/
    - assets/icon/
    - assets/lottie/
    - assets/translations/

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Manrope-Light.ttf
          weight: 300
        - asset: assets/fonts/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope-ExtraBold.ttf
          weight: 800
